[book]
authors = ["Luca Visentin"]
language = "en"
multilingual = false
src = "src"
title = "Data Stewardship Knowledgebase"

[preprocessor.emoji]
# select renderers
renderer = ["html"]

[output.html]
default-theme="dark"
preferred-dark-theme = "ayu"

[preprocessor.callouts]

[preprocessor.emojicodes]

